### ISSUE TITLE
Possible to contribute?

### ISSUE THREAD

**Issue by NoahMLoomis** [numbers007/longtrailsmap#2]
Amazing project. Is it possible to add trails? is there a contribution guideline. Maybe a more important question, is this project still maintained?

**Comment by numbershikes** [comment]
Hello, thanks for the kind words. My [OpenLongTrails.org](https://www.openlongtrails.org/) (OLT) project, which includes [LongTrailsMap.net](https://www.longtrailsmap.net/map) (LTM), is still maintained, but has certainly fallen into neglect. Here's the overall Contributing FAQ: http://www.longtrailswiki.net/wiki/FAQ:_Participating_in_OpenLongTrails. There is no guideline for code contributions, and no direct way for users to contribute trails to the map. There is, however, a process for helping to review trails from the lengthy [List of Trails to Review](http://www.longtrailswiki.net/wiki/List_of_Trails_to_Review) in order to move them to the [List of Long Trails](http://www.longtrailswiki.net/wiki/List_of_Long_Trails), at which point they can be added to LTM. Here's the list of [criteria](http://www.longtrailswiki.net/wiki/OpenLongTrails_Long_Trails_Criteria) that are used to determine which trails to include in the project.

I've recently taken the first steps toward rewriting LTM from scratch in React, but it will probably be awhile before a repo for it is up. The version of the site that's in this repo is the second website I ever built, and the code is not particularly maintainable. Also, the structure of the current site consumes a huge amount of memory in the user's browser, partly due to the fact that it uses a separate layer for each trail. v2 should include multiple trails per layer.

Are you interested in contributing to the React version of LTM? Let me know and I can make a note to reach out once development is underway. My React skills are still at a fairly novice level (frontend has never been my focus), and I would be glad to have another contributor!

**Comment by NoahMLoomis** [comment]
Thanks for the response, I work with React and would be glad to contribute to the new version! I think that this project with a bit more exposure could become a hugely used resource for hikers to find new trails. Please reach out when the repo gets created and development is under way
